version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    ports:
      - "5044:5044"
    volumes:
      - ./payment/logs:/src/payment/logs
      - ./products/logs:/src/products/logs
    depends_on:
      - elasticsearch
      - kibana

  api-gateway:
    container_name: api-gateway
    build: "./api-gateway"
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - PRODUCTS_API_URL=http://products:3000
      - PAYMENT_API_URL=http://payment:3000
    networks:
      - backend
    depends_on:
      - products
      - payment

  products:
    container_name: products
    build: "./products"
    environment:
      - PORT=3000
    networks:
      - backend
    volumes:
      - ./products/logs:/myapp/logs
    depends_on:
      - elasticsearch

  payment:
    container_name: payment
    build: "./payment"
    environment:
      - PORT=3000
    networks:
      - backend
    volumes:
      - ./payment/logs:/myapp/logs
    depends_on:
      - elasticsearch

networks:
  backend:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
