version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '4090:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    ports:
      - "5044:5044"
    volumes:
      - ./payment/logs:/src/payment/logs
      - ./products/logs:/src/products/logs
    depends_on:
      - elasticsearch
      - kibana

  api-gateway:
    container_name: api-gateway
    build: "./api-gateway"
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - PRODUCTS_API_URL=http://products:3000
      - PAYMENT_API_URL=http://payment:3000
    networks:
      - backend
    depends_on:
      - products
      - payment

  products:
    container_name: products
    build: "./products"
    environment:
      - PORT=3000
    networks:
      - backend
    volumes:
      - ./products/logs:/myapp/logs
    depends_on:
      - elasticsearch

  payment:
    container_name: payment
    build: "./payment"
    environment:
      - PORT=3000
    networks:
      - backend
    volumes:
      - ./payment/logs:/myapp/logs
    depends_on:
      - elasticsearch

networks:
  backend:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
